version: '3.7'
services:
  redis:
    image: redis
    container_name: redis_logbook
    networks:
      - local
    ports:
      - '6379:6379'
  postgres:
    image: postgres
    container_name: postgres_logbook
    volumes:
      - ${POSTGRES_VOLUME}
    networks:
      - local
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  pgadmin4:
    image: dpage/pgadmin4
    networks:
      - local
    container_name: pgadmin4_logbook
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: user
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - '16543:80'
networks:
  local:
    driver: bridge
