server:
  port: 8085

spring:
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"
  application:
    name: logbook
  jackson:
    default-property-inclusion: non_null
    serialization:
      INDENT_OUTPUT: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    mapper:
      default-view-inclusion: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/logbook
    hikari:
      maximum-pool-size: 5
  cache:
    type: ehcache
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region.factory_class: org.hibernate.cache.ehcache.internal.EhcacheRegionFactory
          ehcache:
            missing_cache_strategy: create
        temp:
          use_jdbc_metadata_defaults: false
        hbm2ddl:
          auto: update

management:
  health:
    defaults:
      enabled: false
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info, health, prometheus
    jmx:
      exposure:
        exclude: "*"
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
